Lightwerk:
  SurfRunner:
    notification:
      hipChat:
#        authToken: 'Please define this value in root/Configuration/Settings.yaml'
#        room: 1234
#        user: UserName
#        frontendUrl: 'http://.../#/deployment/'

        deploymentStarted:
          enabled: 0
          templatePathAndFilename: Packages/Application/Lightwerk.SurfRunner/Resources/Private/Templates/Notification/HipChat/DeploymentStarted.html

        deploymentFinished:
          enabled: 0
          templatePathAndFilename: Packages/Application/Lightwerk.SurfRunner/Resources/Private/Templates/Notification/HipChat/DeploymentFinished.html

#        'git@git.domain.de:namepsace/project.git':
#          deploymentStarted:
#            room: 123
#            user: UserName
#            authToken: ...
#            ...
#          deploymentFinished:
#            ...