Lightwerk:
  SurfRunner:
    notification:
      hipChat:
#        privateToken: 'Please define this value in root/Configuration/Settings.yaml'
#        frontendUrl: 'http://.../#/deployment/'
        deploymentStarted:
          enabled: 0
          templatePathAndFilename: Packages/Application/Lightwerk.SurfRunner/Resources/Private/Templates/Notification/HipChat/DeploymentStarted.txt
#          room: 1234
#          user: UserName
        deploymentFinished:
          enabled: 0
          templatePathAndFilename: Packages/Application/Lightwerk.SurfRunner/Resources/Private/Templates/Notification/HipChat/DeploymentFinished.txt
#          room: 1234
#          user: UserName