Lightwerk:
  SurfRunner:
    notification:
      hipChat:
        templatePathAndFilename: resource://Lightwerk.SurfRunner/Private/Templates/Notification/HipChat.html
#        authToken: 'Please define this value in root/Configuration/Settings.yaml'
#        room: 1234
#        user: UserName
#        frontendUrl: 'http://.../'

        deploymentStarted:
          enabled: 0

        deploymentFinished:
          enabled: 0

#        'git@git.domain.de:namepsace/project.git':
#          deploymentStarted:
#            room: 123
#            user: UserName
#            authToken: ...
#            ...
#          deploymentFinished:
#            ...

      email:
        templatePathAndFilename: resource://Lightwerk.SurfRunner/Private/Templates/Notification/Email.html
#        frontendUrl: 'http://.../'
#        to:
#          surfCaptain@email.de: 'Last Name, First Name'
#        from:
#          surfCaptain@email.de: 'Last Name, First Name'
#        cc:
#          ...
#        bcc:
#          ...

        deploymentStarted:
          enabled: 0

        deploymentFinished:
          enabled: 0